### ISSUE TITLE
Documentation for 1.x outline

### ISSUE THREAD

**Issue by jmfurlott** [reactjs/react-autocomplete#148]
It is true that the `PropTypes` and examples are more than enough for most users to get started, but is there any initiative to provide documentation?

I would be happy to help out but I wanted to ask some of the maintainers if they have an outline or anything started with sections that are more bitesized for contributing to.

**Comment by CMTegner** [comment]
Argh, you got us! We were so happy pretending that "read the code" was an excuse for missing documentation! :p I've added this to the 1.1.0 milestone, since I've been meaning to create this issue for a while.

If you feel like helping out then a good starting point would be to simply list all the propTypes (I think they're all there, but best to double check the code) and provide a short explanation. I think the first version of the docs could just be put in the README.

**Comment by CMTegner** [comment]
The readme has seen a lot of love lately. AFAIK this issue is no longer applicable. Just reopen if I'm wrong!
