### ISSUE TITLE
Uncaught TypeError: Cannot read property 'ownerDocument' of null

### ISSUE THREAD

**Issue by maksimsemenov** [reactjs/react-autocomplete#176]
This error occurs when user selects an item from the menu and then continues typing. I guess that using reference callback on menu object instead of string could solve this problem

**Comment by CMTegner** [comment]
Hi! Could you please provide a gist with a reduced test case?

**Comment by maksimsemenov** [comment]
Hey, sorry. What do you mean "reduced test case"? I'm novice in contributing so I don't know how it works yet.

**Comment by mwilliamson-healx** [comment]
I get this problem when using a portal to render the menu. Since the menu is actually rendered in `componentDidUpdate`, then the `componentDidUpdate` of `Autocomplete` may get triggered first. Then `findDOMNode(itemNode)` is `null` in `maybeScrollItemIntoView()`, which eventually causes the null error.

I'll produce a test case if I get time, but thought it worth describing the problem anyway.

**Comment by lordalaqua** [comment]
Ran into this issue as well, PR above fixes it nicely. Is there any estimate for a next release including this fix?

**Comment by johannessjoberg** [comment]
+1

**Comment by ShyamRaj** [comment]
I got this problem as well, Is the PR merged?

**Comment by mir3z** [comment]
I still get this issue. Are you gonna fix that?

**Comment by CMTegner** [comment]
As I explained in #256, this is likely due to the fact that you're not rendering all the items in your `renderMenu` implementation. Please open a new issue if you belive there's still a bug to be fixed.

**Comment by mir3z** [comment]
Here you go: #261
