### ISSUE TITLE
createClass, findDOMNode, and string refs, oh my!

### ISSUE THREAD

**Issue by fredguest** [reactjs/react-autocomplete#223]
Looking at the source, it's a little surprising to see the use of these methods:

- **createClass**
https://github.com/facebook/react/issues/8854
"To reduce the bundle size, we need to remove the APIs that we don't recommend, such as createClass and React.DOM.* helpers."
- **findDOMNode**
https://facebook.github.io/react/docs/react-dom.html#finddomnode
"findDOMNode is an escape hatch used to access the underlying DOM node. In most cases, use of this escape hatch is discouraged because it pierces the component abstraction."
- **string refs**
https://facebook.github.io/react/docs/refs-and-the-dom.html#legacy-api-string-refs
"If you worked with React before, you might be familiar with an older API where the ref attribute is a string, like "textInput", and the DOM node is accessed as this.refs.textInput. We advise against it because string refs have some issues, are considered legacy, and are likely to be removed in one of the future releases."

I see there is an "experimental-rewrite" branch https://github.com/reactjs/react-autocomplete/tree/experimental-rewrite but it doesn't seem to address any of these issues.

What is the reasoning behind the continued use of these discouraged and soon to be deprecated or extracted APIs?

**Comment by sprjr** [comment]
The reasoning is most likely that the project has been 'stable' for awhile and mostly maintained by anyone who needs to drive things forward. I've not been able to carve out much time to invest here, although we can add anyone willing to the project (I believe I can or @ryanflorence can) both here and on npm.

The APIs you listed above have just been part of the module pre-dating their deprecation is all :)

**Comment by fredguest** [comment]
Ok cool that makes sense. I wasn't sure if there was something philosophical behind it because this library seems pretty actively maintained and that `experimental-rewrite` branch is pretty new.

**Comment by luislikescoffee** [comment]
@fredguest I've opened a merge request that removes createClass and getting propTypes from the main react package (https://github.com/reactjs/react-autocomplete/pull/225)

**Comment by donysukardi** [comment]
@luislikescoffee Sorry, I didn't know someone else was working on it too. In addition to React.createClass and React.PropTypes, I also refactored string refs to use refs assignment instead.

**Comment by luislikescoffee** [comment]
@donysukardi No worries, just happy to see it's getting fixed!

**Comment by donysukardi** [comment]
I'm still working on updating the test suite due to the refs changes though.

**Comment by silicakes** [comment]
@luislikescoffee @donysukardi - both of your PRs have conflicts due to the recent update.

**Comment by donysukardi** [comment]
It seems that @CMTegner has done the refactoring to use callback refs by himself, which makes the PR no longer valid.

**Comment by CMTegner** [comment]
I haven't had much time to go through PRs lately, so I've been focusing my time on bugs and low hanging fruits that cause a lot of noise (in the form of issues). I hadn't originally planned on spending any time on `refs` in v1, but it had to be done to pave way for the imperative API (the lack of which was causing a lot of pain).

When it comes to `createClass`, `propTypes`, `findDOMNode`, et al.: we very much appreciate PRs, but since we have limited time to cut releases we tend to pick the changes carefully. As @sprjr stated: the v1 branch of this project is mostly stable and mainly sees bugfixes and occasional improvements.

I intend to outline v2 soon so that we can visualise what needs to be done and start pulling in changes. The target will most likely be React 16, so `createClass` and `propTypes` rewrites will naturally be included.
