### ISSUE TITLE
reference to <input>

### ISSUE THREAD

**Issue by tusharchhibber** [reactjs/react-autocomplete#228]
So I know I can do something like this to get a handle on input textfield:

input className={className} ref='input' 

and then use the handle to focus on input textfield:
this.refs.input.nameInput.focus()

Using the react-autocomplete, i m sending this in the inputProps

inputProps: {
        className: 'uk-input ' + errorClassName,
        type: 'text',
        onBlur: this.handleBlur,
        ref: 'input'
}

And trying to get a hold of <input> to focus on by:
this.refs.input.nameInput.focus()

But it is not working as 'input' is not being added to refs object... I am assuming ref: 'input' is not the same as ref='input'
And ref: {(input) => { this.nameInput = input }} can't be done as explained in this link:
https://facebook.github.io/react/docs/refs-and-the-dom.html

**Comment by vorlov** [comment]
```javascript
<Autocomplete
    ref={ inputRef }
/>

const inputRef = (ac) => { this.input = ac.refs.input }
```

**Comment by tusharchhibber** [comment]
Hi @vorlov  thanks for your reply. It did indeed not complain about syntactic problems but it throws this error:

Uncaught TypeError: Cannot read property 'refs' of null

I am using 

render () {
  const inputRef = (ac) => { this.input = ac.refs.input }
  return (
   <Autocomplete
     ref={ inputRef }
    />
  )
}

in one file and I want the input text field to autofocus on mounting of the Autocomplete. So I am using this code in Autocomplete file:

componentDidMount () {
  this.input.focus()
}

Any ideas...

**Comment by CMTegner** [comment]
@tusharchhibber you overlooked this part in the documentation:

>React will call the ref callback with the DOM element when the component mounts, and call it with null when it unmounts.

You need to check if your `ref` callback is fired with an actual element or `null`. We don't suggest using `Autocomplete`'s internal refs. They're not documented and they'll likely be renamed/removed in the near future. That being said, I won't blame you for using them, since it's the only way you can access the imperative `<input>` API.

I hope to have time this weekend to add new methods to `Autocomplete` so you won't have to use refs directly.

**Comment by CMTegner** [comment]
Version 1.5.0 has `focus`, `blur`, `setSelectionRange`, and a few other methods you are used to seeing on `<input>` elements. Check the [documentation](https://github.com/reactjs/react-autocomplete/#imperative-api) for an example.
