### ISSUE TITLE
error position fixed when scroll

### ISSUE THREAD

**Issue by meninjanho4788** [reactjs/react-autocomplete#255]
please review when you click to show autocomplete and scroll after.
The autocomple move down when scroll down

**Comment by CMTegner** [comment]
Hi! You probably already discovered this (since you've closed the issue), but you have full control over the menu's styling via either [`props.menuStyle`](https://github.com/reactjs/react-autocomplete/#menustyle-object-optional) and/or [`props.renderMenu`](https://github.com/reactjs/react-autocomplete/#rendermenu-function-optional).
