### ISSUE TITLE
Why does `getItemValue` has to return string?

### ISSUE THREAD

**Issue by mir3z** [reactjs/react-autocomplete#260]
As per title - what if I need to return an object and have this object in `onSelect`

**Comment by CMTegner** [comment]
Hi! `getItemValue` needs to return a string because its return value is used to determine which item to highlight (by matching the input text with the item display value). To retrieve the selected source object when an item is selected, simply use the second argument passed to [`onSelect`](https://github.com/reactjs/react-autocomplete#onselect-function-optional).
