### ISSUE TITLE
Cannot read property 'ownerDocument' of null

### ISSUE THREAD

**Issue by LyTranCong** [reactjs/react-autocomplete#287]
I see that it already fixed in 1.4.2 but now 1.7.2 this error popup again!

**Comment by ma-pe** [comment]
same here.

**Comment by JorisPhilipsen** [comment]
I have this problem as well, can someone merge this please?

**Comment by Slogo** [comment]
I had this issue but was able to work around it.

In my case I had code like this:

```
renderItem={(item, isHighlighted) => (
  <MyFunctionalComponent key={item.id} item={item} highlighted={isHighlighted}/>
)}
```


The problem is that the autocomplete will take the rendered items and apply a ref to them. It calls cloneElement with your rendered item as the element to clone and a ref as an additional property to apply. However, you cannot apply a ref to a functional component (see: https://reactjs.org/docs/refs-and-the-dom.html ). What ended up happening is my refs would be set to null and then later you'd get the error when trying to scroll the highlighted menu item into view (a useful feature).

My solution was simple:

```
renderItem={(item, isHighlighted) => (
  <div key={item.id}>
    <MyFunctionalComponent key={item.id} item={item} highlighted={isHighlighted}/>
  </div>
)}
```

With this fix the rendered Item can properly a ref applied to it and the issue is avoided. In theory I could have also made MyFunctionalComponent into a non-functional component.

**Comment by CMTegner** [comment]
This is already documented in [`props.renderMenu`](https://github.com/reactjs/react-autocomplete#rendermenu-function-optional):

>Ensure the returned tree includes every entry in items or else the highlight order and keyboard navigation logic will break.

Please open a new ticket with a detailed explanation if you're experiencing problems that aren't covered in the documentation.

**Comment by avindra** [comment]
@CMTegner is there a plan to support limiting the list size?  I think https://github.com/reactjs/react-autocomplete/issues/374 is going for a similar ask.

When lists have hundreds of items, it quickly becomes unusable as the browser struggles to render the list

**Comment by avindra** [comment]
@CMTegner  that should be called out a bit more clearly in the docs... totally glazed over that sentence. Are you open to a PR for a doc fix?
