### ISSUE TITLE
Problems with cursor position in Internet Explorer

### ISSUE THREAD

**Issue by shiitake** [reactjs/react-autocomplete#80]
When you are typing in the input field if you match an item by more than a few characters it will narrow the search results and highlight the top option.  Once this happens if you try to type additional letters the cursor will have moved to the first position of the text field. 

This can be demonstrated using the examples linked on the site: 
https://reactcommunity.org/react-autocomplete/async-data/

**Comment by CMTegner** [comment]
Reproducible in IE11 on Windows 8.1:

1. Navigate to https://reactcommunity.org/react-autocomplete/async-data/
2. Type 'A' in the input
3. Observe that the 'Alabama' is highlighted in the autocomplete menu
4. Type 'L' in the input
5. Observe that the input value is 'LA', expected: 'AL'

I'm not sure what causes this, but if no one else has time I'll try to have a look this weekend.

**Comment by HenriJ** [comment]
Hi @CMTegner . Did you have any luck finding the root cause ? We are stuck because of this problem too, and can have a look also if it can help.

**Comment by CMTegner** [comment]
I've had little look at the problem. My initial suspicion was that `input#setSelectionRange()` (which is invoked when Autocomplete fills the input with the top result) was bugging out in IE, and that's sort of what's happening. To exclude the possibility of `setSelectionRange()` being completely borked on IE I made a quick test page:

```html
<!doctype html>
<html>
<head>
  <title>setSelectionRange test</title>
</head>
<body>
  <input type="text" value="foobar">
  <script type="text/javascript">
    var input = document.querySelector('input');
    input.focus();
    input.setSelectionRange(1, 6);
  </script>
</body>
</html>
```

Load that up in IE11, type a character, success.

After having played around with `setSelectionRange` for a while, I came to the conclusion that if you create a range with a non-zero length, the caret (or at least the internal caret state position) is moved to position 0 (the start of the input). In other words, if you use `setSelectionRange` to place the caret (end = start) after updating the input value, things work as expected. The problem occurs when you create an actual text selection range (end > start).

My current theory is that Autocomplete's usage of `setSelectionRange()` is somehow interfering with React's focus/caret positioning logic. I haven't had time to dig any deeper.

**Comment by HenriJ** [comment]
Not sure exactly why it behaves like that (as you say, it might be interferences between React and setSelectionRange), but I found a workaround that seems to fix the issue : forcing the position of the caret in the callback of the setState() that was causing the problem.

@CMTegner @shiitake  Could you confirm that https://github.com/HenriJ/react-autocomplete/commit/3d5a3e890b6c455df89351656a50b9dee17238bf fixes the issue for you ?

**Comment by CMTegner** [comment]
@HenriJ I don't even want to know what made you try that... I swear I tried just about everything yesterday in an attempt to find a workaround. Even after having tested your workaround for a couple of hours I still don't 100% understand why it works. The closest I've come to explain it is this:

<img width="577" alt="screen shot 2016-03-24 at 12 14 24" src="https://cloud.githubusercontent.com/assets/820552/14016449/cce8719e-f1c0-11e5-838e-ab1e8d1be37b.png">

That's Chrome (on Mac) and IE11 side by side. You can see that the `setState()` callback in `handleKeyDown()` reports the correct caret/selection state in Chrome, but IE reports it as (0,0). Ignore the non-deterministic autocomplete suggestions, I eventually reduced the list in `lib/utils.js` to exclude that as a possibility.

Anyway, huge thanks! I made [a PR](https://github.com/reactjs/react-autocomplete/pull/85) which I need @sprjr to look at ASAP, since this is a blocker for IE usage.

**Comment by sprjr** [comment]
Sorry again for the delays here. This has been in 1.0.0-rc2, which I've tagged and published to npm. Unfortunately I'm headed to China for most of the rest of the month. We should probably chat with @ryanflorence about adding more contributors to the project if something more pressing comes up. There's a backlog of issues and PRs open that I'd like to try and work through as well, to keep the component moving and up to date.

Hopefully this release unblocks folks!

**Comment by CMTegner** [comment]
@sprjr no worries, I'm happy just seeing some movement at all :)
